#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="anaokul")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertkitap(kitap instance);
  partial void Updatekitap(kitap instance);
  partial void Deletekitap(kitap instance);
  partial void Inserthasta(hasta instance);
  partial void Updatehasta(hasta instance);
  partial void Deletehasta(hasta instance);
  partial void Insertogrenci(ogrenci instance);
  partial void Updateogrenci(ogrenci instance);
  partial void Deleteogrenci(ogrenci instance);
  partial void Inserthaber_resim(haber_resim instance);
  partial void Updatehaber_resim(haber_resim instance);
  partial void Deletehaber_resim(haber_resim instance);
  partial void Insertetkinlik_resim(etkinlik_resim instance);
  partial void Updateetkinlik_resim(etkinlik_resim instance);
  partial void Deleteetkinlik_resim(etkinlik_resim instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["anaokulConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<kitap> kitaps
	{
		get
		{
			return this.GetTable<kitap>();
		}
	}
	
	public System.Data.Linq.Table<hasta> hastas
	{
		get
		{
			return this.GetTable<hasta>();
		}
	}
	
	public System.Data.Linq.Table<ogrenci> ogrencis
	{
		get
		{
			return this.GetTable<ogrenci>();
		}
	}
	
	public System.Data.Linq.Table<haber_resim> haber_resims
	{
		get
		{
			return this.GetTable<haber_resim>();
		}
	}
	
	public System.Data.Linq.Table<etkinlik_resim> etkinlik_resims
	{
		get
		{
			return this.GetTable<etkinlik_resim>();
		}
	}
	
	public System.Data.Linq.Table<duyuru_resim> duyuru_resims
	{
		get
		{
			return this.GetTable<duyuru_resim>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kitap")]
public partial class kitap : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _k_adi;
	
	private string _yazar;
	
	private string _k_turu;
	
	private string _yayinevi;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onk_adiChanging(string value);
    partial void Onk_adiChanged();
    partial void OnyazarChanging(string value);
    partial void OnyazarChanged();
    partial void Onk_turuChanging(string value);
    partial void Onk_turuChanged();
    partial void OnyayineviChanging(string value);
    partial void OnyayineviChanged();
    #endregion
	
	public kitap()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k_adi", DbType="NChar(30)")]
	public string k_adi
	{
		get
		{
			return this._k_adi;
		}
		set
		{
			if ((this._k_adi != value))
			{
				this.Onk_adiChanging(value);
				this.SendPropertyChanging();
				this._k_adi = value;
				this.SendPropertyChanged("k_adi");
				this.Onk_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yazar", DbType="NChar(30)")]
	public string yazar
	{
		get
		{
			return this._yazar;
		}
		set
		{
			if ((this._yazar != value))
			{
				this.OnyazarChanging(value);
				this.SendPropertyChanging();
				this._yazar = value;
				this.SendPropertyChanged("yazar");
				this.OnyazarChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_k_turu", DbType="NChar(30)")]
	public string k_turu
	{
		get
		{
			return this._k_turu;
		}
		set
		{
			if ((this._k_turu != value))
			{
				this.Onk_turuChanging(value);
				this.SendPropertyChanging();
				this._k_turu = value;
				this.SendPropertyChanged("k_turu");
				this.Onk_turuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yayinevi", DbType="NChar(30)")]
	public string yayinevi
	{
		get
		{
			return this._yayinevi;
		}
		set
		{
			if ((this._yayinevi != value))
			{
				this.OnyayineviChanging(value);
				this.SendPropertyChanging();
				this._yayinevi = value;
				this.SendPropertyChanged("yayinevi");
				this.OnyayineviChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hasta")]
public partial class hasta : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _ogrenci_no;
	
	private string _g_tarih;
	
	private string _c_tarih;
	
	private string _rahatsizlik;
	
	private string _tedavi;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onogrenci_noChanging(string value);
    partial void Onogrenci_noChanged();
    partial void Ong_tarihChanging(string value);
    partial void Ong_tarihChanged();
    partial void Onc_tarihChanging(string value);
    partial void Onc_tarihChanged();
    partial void OnrahatsizlikChanging(string value);
    partial void OnrahatsizlikChanged();
    partial void OntedaviChanging(string value);
    partial void OntedaviChanged();
    #endregion
	
	public hasta()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ogrenci_no", DbType="NChar(30)")]
	public string ogrenci_no
	{
		get
		{
			return this._ogrenci_no;
		}
		set
		{
			if ((this._ogrenci_no != value))
			{
				this.Onogrenci_noChanging(value);
				this.SendPropertyChanging();
				this._ogrenci_no = value;
				this.SendPropertyChanged("ogrenci_no");
				this.Onogrenci_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_g_tarih", DbType="NChar(30)")]
	public string g_tarih
	{
		get
		{
			return this._g_tarih;
		}
		set
		{
			if ((this._g_tarih != value))
			{
				this.Ong_tarihChanging(value);
				this.SendPropertyChanging();
				this._g_tarih = value;
				this.SendPropertyChanged("g_tarih");
				this.Ong_tarihChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_tarih", DbType="NChar(30)")]
	public string c_tarih
	{
		get
		{
			return this._c_tarih;
		}
		set
		{
			if ((this._c_tarih != value))
			{
				this.Onc_tarihChanging(value);
				this.SendPropertyChanging();
				this._c_tarih = value;
				this.SendPropertyChanged("c_tarih");
				this.Onc_tarihChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rahatsizlik", DbType="NChar(30)")]
	public string rahatsizlik
	{
		get
		{
			return this._rahatsizlik;
		}
		set
		{
			if ((this._rahatsizlik != value))
			{
				this.OnrahatsizlikChanging(value);
				this.SendPropertyChanging();
				this._rahatsizlik = value;
				this.SendPropertyChanged("rahatsizlik");
				this.OnrahatsizlikChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tedavi", DbType="NChar(30)")]
	public string tedavi
	{
		get
		{
			return this._tedavi;
		}
		set
		{
			if ((this._tedavi != value))
			{
				this.OntedaviChanging(value);
				this.SendPropertyChanging();
				this._tedavi = value;
				this.SendPropertyChanged("tedavi");
				this.OntedaviChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ogrenci")]
public partial class ogrenci : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _ogrenci_no;
	
	private string _ad_soyad;
	
	private string _cinsiyet;
	
	private string _tc_no;
	
	private string _dogum_tarih;
	
	private string _veli_adi;
	
	private string _donem;
	
	private string _kan_grub;
	
	private string _telefon;
	
	private string _şube;
	
	private string _adres;
	
	private string _ogretmen;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onogrenci_noChanging(string value);
    partial void Onogrenci_noChanged();
    partial void Onad_soyadChanging(string value);
    partial void Onad_soyadChanged();
    partial void OncinsiyetChanging(string value);
    partial void OncinsiyetChanged();
    partial void Ontc_noChanging(string value);
    partial void Ontc_noChanged();
    partial void Ondogum_tarihChanging(string value);
    partial void Ondogum_tarihChanged();
    partial void Onveli_adiChanging(string value);
    partial void Onveli_adiChanged();
    partial void OndonemChanging(string value);
    partial void OndonemChanged();
    partial void Onkan_grubChanging(string value);
    partial void Onkan_grubChanged();
    partial void OntelefonChanging(string value);
    partial void OntelefonChanged();
    partial void OnşubeChanging(string value);
    partial void OnşubeChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    partial void OnogretmenChanging(string value);
    partial void OnogretmenChanged();
    #endregion
	
	public ogrenci()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ogrenci_no", DbType="NChar(30)")]
	public string ogrenci_no
	{
		get
		{
			return this._ogrenci_no;
		}
		set
		{
			if ((this._ogrenci_no != value))
			{
				this.Onogrenci_noChanging(value);
				this.SendPropertyChanging();
				this._ogrenci_no = value;
				this.SendPropertyChanged("ogrenci_no");
				this.Onogrenci_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad_soyad", DbType="NChar(30)")]
	public string ad_soyad
	{
		get
		{
			return this._ad_soyad;
		}
		set
		{
			if ((this._ad_soyad != value))
			{
				this.Onad_soyadChanging(value);
				this.SendPropertyChanging();
				this._ad_soyad = value;
				this.SendPropertyChanged("ad_soyad");
				this.Onad_soyadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cinsiyet", DbType="NChar(30)")]
	public string cinsiyet
	{
		get
		{
			return this._cinsiyet;
		}
		set
		{
			if ((this._cinsiyet != value))
			{
				this.OncinsiyetChanging(value);
				this.SendPropertyChanging();
				this._cinsiyet = value;
				this.SendPropertyChanged("cinsiyet");
				this.OncinsiyetChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tc_no", DbType="NChar(30)")]
	public string tc_no
	{
		get
		{
			return this._tc_no;
		}
		set
		{
			if ((this._tc_no != value))
			{
				this.Ontc_noChanging(value);
				this.SendPropertyChanging();
				this._tc_no = value;
				this.SendPropertyChanged("tc_no");
				this.Ontc_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dogum_tarih", DbType="NChar(30)")]
	public string dogum_tarih
	{
		get
		{
			return this._dogum_tarih;
		}
		set
		{
			if ((this._dogum_tarih != value))
			{
				this.Ondogum_tarihChanging(value);
				this.SendPropertyChanging();
				this._dogum_tarih = value;
				this.SendPropertyChanged("dogum_tarih");
				this.Ondogum_tarihChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veli_adi", DbType="NChar(30)")]
	public string veli_adi
	{
		get
		{
			return this._veli_adi;
		}
		set
		{
			if ((this._veli_adi != value))
			{
				this.Onveli_adiChanging(value);
				this.SendPropertyChanging();
				this._veli_adi = value;
				this.SendPropertyChanged("veli_adi");
				this.Onveli_adiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donem", DbType="NChar(30)")]
	public string donem
	{
		get
		{
			return this._donem;
		}
		set
		{
			if ((this._donem != value))
			{
				this.OndonemChanging(value);
				this.SendPropertyChanging();
				this._donem = value;
				this.SendPropertyChanged("donem");
				this.OndonemChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kan_grub", DbType="NChar(30)")]
	public string kan_grub
	{
		get
		{
			return this._kan_grub;
		}
		set
		{
			if ((this._kan_grub != value))
			{
				this.Onkan_grubChanging(value);
				this.SendPropertyChanging();
				this._kan_grub = value;
				this.SendPropertyChanged("kan_grub");
				this.Onkan_grubChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="NChar(30)")]
	public string telefon
	{
		get
		{
			return this._telefon;
		}
		set
		{
			if ((this._telefon != value))
			{
				this.OntelefonChanging(value);
				this.SendPropertyChanging();
				this._telefon = value;
				this.SendPropertyChanged("telefon");
				this.OntelefonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_şube", DbType="NChar(10)")]
	public string şube
	{
		get
		{
			return this._şube;
		}
		set
		{
			if ((this._şube != value))
			{
				this.OnşubeChanging(value);
				this.SendPropertyChanging();
				this._şube = value;
				this.SendPropertyChanged("şube");
				this.OnşubeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="NChar(50)")]
	public string adres
	{
		get
		{
			return this._adres;
		}
		set
		{
			if ((this._adres != value))
			{
				this.OnadresChanging(value);
				this.SendPropertyChanging();
				this._adres = value;
				this.SendPropertyChanged("adres");
				this.OnadresChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ogretmen", DbType="NChar(30)")]
	public string ogretmen
	{
		get
		{
			return this._ogretmen;
		}
		set
		{
			if ((this._ogretmen != value))
			{
				this.OnogretmenChanging(value);
				this.SendPropertyChanging();
				this._ogretmen = value;
				this.SendPropertyChanged("ogretmen");
				this.OnogretmenChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.haber_resim")]
public partial class haber_resim : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _resimyolu;
	
	private string _h_yazi;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnresimyoluChanging(string value);
    partial void OnresimyoluChanged();
    partial void Onh_yaziChanging(string value);
    partial void Onh_yaziChanged();
    #endregion
	
	public haber_resim()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resimyolu", DbType="NVarChar(50)")]
	public string resimyolu
	{
		get
		{
			return this._resimyolu;
		}
		set
		{
			if ((this._resimyolu != value))
			{
				this.OnresimyoluChanging(value);
				this.SendPropertyChanging();
				this._resimyolu = value;
				this.SendPropertyChanged("resimyolu");
				this.OnresimyoluChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_yazi", DbType="NVarChar(MAX)")]
	public string h_yazi
	{
		get
		{
			return this._h_yazi;
		}
		set
		{
			if ((this._h_yazi != value))
			{
				this.Onh_yaziChanging(value);
				this.SendPropertyChanging();
				this._h_yazi = value;
				this.SendPropertyChanged("h_yazi");
				this.Onh_yaziChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.etkinlik_resim")]
public partial class etkinlik_resim : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _resimyolu;
	
	private string _r_yazi;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnresimyoluChanging(string value);
    partial void OnresimyoluChanged();
    partial void Onr_yaziChanging(string value);
    partial void Onr_yaziChanged();
    #endregion
	
	public etkinlik_resim()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resimyolu", DbType="NVarChar(50)")]
	public string resimyolu
	{
		get
		{
			return this._resimyolu;
		}
		set
		{
			if ((this._resimyolu != value))
			{
				this.OnresimyoluChanging(value);
				this.SendPropertyChanging();
				this._resimyolu = value;
				this.SendPropertyChanged("resimyolu");
				this.OnresimyoluChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_yazi", DbType="NVarChar(MAX)")]
	public string r_yazi
	{
		get
		{
			return this._r_yazi;
		}
		set
		{
			if ((this._r_yazi != value))
			{
				this.Onr_yaziChanging(value);
				this.SendPropertyChanging();
				this._r_yazi = value;
				this.SendPropertyChanged("r_yazi");
				this.Onr_yaziChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.duyuru_resim")]
public partial class duyuru_resim
{
	
	private System.Nullable<int> _id;
	
	private string _resimyolu;
	
	private string _d_yazi;
	
	public duyuru_resim()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
	public System.Nullable<int> id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this._id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resimyolu", DbType="NVarChar(50)")]
	public string resimyolu
	{
		get
		{
			return this._resimyolu;
		}
		set
		{
			if ((this._resimyolu != value))
			{
				this._resimyolu = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_yazi", DbType="NVarChar(MAX)")]
	public string d_yazi
	{
		get
		{
			return this._d_yazi;
		}
		set
		{
			if ((this._d_yazi != value))
			{
				this._d_yazi = value;
			}
		}
	}
}
#pragma warning restore 1591
